### ISSUE TITLE
IntradayContinuous

### ISSUE THREAD

**Issue by tristanfabregas** [wagnertimo/emarketcrawlR#2]
Dear Timo,

Thank you for this great job, however, I can not reproduce your first example using the function "getIntradayContinuousEPEXSPOT"

Here is the error message:
04-28 16:03:04 INFO::getIntradayContinuousEPEXSPOT - Call for:  2017-05-26  and  2017-05-25  | REMEBER 2 dates on site!
2018-04-28 16:03:05 INFO::parseICEPEXSPOT - Parsing Continuous Intraday EPEX website with 2 dates
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 96, 108
De plus : Warning message:
In parseICEPEXSPOT(parsedHtml, product, country) :

Have you any ideas how to fix that ?
Kind regards,
Tristan

**Comment by wagnertimo** [comment]
Hey Tristan,

thank you for your issue request and sorry for the late response.
I am currently involved in another project so I have not enough time to maintain the package closely. Though this is crucial especially for crawler software since the website structure can change.

I will look into that problem for the weekend. 

Best regards
Timo

**Comment by tristanfabregas** [comment]
Hi Timo,

Thank you very much for your reply.
Is your other project also related to time series ?

Kind regards,

Tristan

2018-05-18 19:48 GMT+02:00 Timo Wagner <notifications@github.com>:

**Comment by wagnertimo** [comment]
Hey Tristan,

I looked into the problem and it seems it has to do something with the change in the table structure of the website. For the german market a new index price value (ID1, [source](https://www.epexspot.com/de/presse/press-archive/details/press/Exchange_Council_welcomes_trading_closer_to_real-time_on_UK_market)) was added in January 2018. So I will need to change my crawler logic. I will look into that the following week/weekend, and hopefully fix that bug.

Yes I am working with time series but at another domain. But I am not allowed to tell more :)

Best regards
Timo

**Comment by busiing** [comment]
Hey Timo,
I am a fan of your work. Just wanted to let you know, that people are interested in this work!

Best regards,
Steffen

**Comment by wagnertimo** [comment]
Hey,

thank you Steffen! I try my best to maintain the repo.
I implemented the ID1 column now. So at least the example code should work for now. Haven't found time yet to test further. If there are still some issues inform me.

Best regards
Timo

**Comment by busiing** [comment]
Hey Timo,

thank you for your effort! I can't try it atm since the epex servers seem
to be down.

Best regards
Steffen

2018-06-29 20:05 GMT+02:00 Timo Wagner <notifications@github.com>:
