### ISSUE TITLE
getPHELIXDEFuturesEEX is broken

### ISSUE THREAD

**Issue by JCRichstein** [wagnertimo/emarketcrawlR#3]
Hey Timo,

great work! But to raise an issue: the function getPHELIXDEFuturesEEX, (more specifically getPHELIXDEFuturesForADate) is a bit broken.
You can only ask for Tuesdays to Fridays (at least for some sample weeks in 2018 and 2019), as it otherwise tries to get data from the day before which would be a weekend and not available. Again no expectation that this is fixed. I might try it myself.

Cheers
Jörn

PS: My first diagnosis was wrong, so I updated the issue.

**Comment by JCRichstein** [comment]
Made a suggestion to fix it  #4 .
Cheers
Jörn

**Comment by wagnertimo** [comment]
Thx Jörn for your pull request and improving the library!
I merged it to master ([here](https://github.com/wagnertimo/emarketcrawlR/commit/4eba1e8c5d7d0b5d28f01eefd3c3733c132d9ce9))
I am now on a different project so it is hard for me to maintain it.

Cheers
Timo
